### PR TITLE
Did some polishing

### PR DESCRIPTION
**Pull request by banago**
Hi Stephen,

Firstly, I want to congratulate you on this very good script you've put together. I will be using it on a project very soon and I though I'd do some fixes. 

I renamed the readme to recognise markdown and look better. Also added the "public" keyword to the class methods.

Have a look and if you think they are worth to merge, go ahead and do so :)

Kindly,
Baki

### CODE REVIEW

**Comment by stephenh1988** [comment]
Thanks Banago, I was admittedly very lazy with the ReadMe. I had the methods set to static so they wouldn't be accessible outside the class... but I guess it may be handy for some to be able to do that. Thanks again :).

**Comment by banago** [comment]
Hi Stephen,

Seems I did not what you where trying to do with the static keyword. That's because static is not used for visibilty, like public/protected/private - but means someone case use that static method without instantiating the class first, like so WordPress_Radio_Taxonomy::metabox(). Seems you have exchanged it for the private keyword.

But that's fine and we will try to refine the class further, but you have done wonderful job thus far.

And I really like your events plugin. I might jump on that too to give you a hand.

Talk soon mate.

**Comment by stephenh1988** [comment]
True...  not sure why I made them static now... I'm going to blame it on the fact it was late :D. I'm thinking about adding the ability to create taxonomy - it will require a complete custom AJAX action. 

Thanks! It would be most welcome :D. I need to update the github version (I've fallen behind on the commits :S). The Github repo version is unstable though - the next version of EO is converting venues into taxonomy terms.

**Comment by banago** [comment]
I like the taxonomy creation on the fly.

You need to sync the EO please :)

**Pull request merged**
